// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package products

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson797f9fe8DecodeGithubComProductPagePkgProducts(in *jlexer.Lexer, out *Products) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Products, 0, 1)
			} else {
				*out = Products{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Product
			(v1).UnmarshalTinyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson797f9fe8EncodeGithubComProductPagePkgProducts(out *jwriter.Writer, in Products) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalTinyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Products) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson797f9fe8EncodeGithubComProductPagePkgProducts(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Products) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson797f9fe8EncodeGithubComProductPagePkgProducts(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Products) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson797f9fe8DecodeGithubComProductPagePkgProducts(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Products) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson797f9fe8DecodeGithubComProductPagePkgProducts(l, v)
}
func tinyjson797f9fe8DecodeGithubComProductPagePkgProducts1(in *jlexer.Lexer, out *Product) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "descriptionHtml":
			out.DescriptionHtml = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson797f9fe8EncodeGithubComProductPagePkgProducts1(out *jwriter.Writer, in Product) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"descriptionHtml\":"
		out.RawString(prefix)
		out.String(string(in.DescriptionHtml))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Product) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson797f9fe8EncodeGithubComProductPagePkgProducts1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Product) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson797f9fe8EncodeGithubComProductPagePkgProducts1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Product) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson797f9fe8DecodeGithubComProductPagePkgProducts1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Product) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson797f9fe8DecodeGithubComProductPagePkgProducts1(l, v)
}
